/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/s5kvmAQxsvS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "../components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "../components/ui/avatar";

export default function Component() {
  return (
    <div className="flex flex-col h-screen p-4 pt-24">
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4 md:p-6">
        <Card className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardHeader className="flex flex-row items-center gap-4">
            <Avatar className="w-12 h-12">
              <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <CardTitle className="text-[#4caf50]">John Doe</CardTitle>
              <CardDescription className="text-[#757575]">
                @johndoe
              </CardDescription>
            </div>
          </CardHeader>
          <CardContent className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <div className="text-2xl font-bold text-[#4caf50]">1,234</div>
              <div className="text-sm text-[#757575]">Trees Planted</div>
            </div>
            <div className="grid gap-2">
              <div className="text-2xl font-bold text-[#4caf50]">3rd</div>
              <div className="text-sm text-[#757575]">Rank</div>
            </div>
            <div className="grid gap-2">
              <div className="text-2xl font-bold text-[#4caf50]">12</div>
              <div className="text-sm text-[#757575]">Badges</div>
            </div>
            <div className="grid gap-2">
              <div className="text-2xl font-bold text-[#4caf50]">5</div>
              <div className="text-sm text-[#757575]">Milestones</div>
            </div>
          </CardContent>
          <CardFooter className="grid gap-2">
            <div className="text-sm text-[#757575]">
              Personalized Tip: Plant trees native to your region for better
              survival rates.
            </div>
          </CardFooter>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-[#4caf50]">
              Global Planting Statistics
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-4xl font-bold text-[#4caf50]">2,345,678</div>
            <div className="text-sm text-[#757575]">Total Trees Planted</div>
          </CardContent>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-[#4caf50]">
              Local Weather and Conditions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <div className="text-2xl font-bold text-[#4caf50]">24°C</div>
                <div className="text-sm text-[#757575]">
                  Current Temperature
                </div>
              </div>
              <div className="grid gap-2">
                <div className="text-2xl font-bold text-[#4caf50]">Good</div>
                <div className="text-sm text-[#757575]">Air Quality Index</div>
              </div>
              <div className="grid gap-2">
                <div className="text-2xl font-bold text-[#4caf50]">20%</div>
                <div className="text-sm text-[#757575]">Chance of Rain</div>
              </div>
              <div className="grid gap-2">
                <div className="text-2xl font-bold text-[#4caf50]">
                  Light Wind
                </div>
                <div className="text-sm text-[#757575]">Wind Conditions</div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-2">
          <CardHeader>
            <CardTitle className="text-[#4caf50]">
              Available Planting Locations
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="h-[400px] rounded-lg">
              <div />
            </div>
          </CardContent>
        </Card>
        <Card className="col-span-1 md:col-span-2 lg:col-span-1">
          <CardHeader>
            <CardTitle className="text-[#4caf50]">
              Tree Planting Guide
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <Avatar className="w-12 h-12">
                  <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                  <AvatarFallback>AI</AvatarFallback>
                </Avatar>
                <div className="grid gap-1">
                  <div className="font-medium text-[#4caf50]">
                    Tree Planting Assistant
                  </div>
                  <div className="text-sm text-[#757575]">
                    I'm here to guide you through the tree planting process.
                  </div>
                </div>
              </div>
              <div className="border rounded-lg p-4">
                <div className="flex items-start gap-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AI</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[#4caf50]">
                        Tree Planting Assistant
                      </div>
                      <div className="text-xs text-[#757575]">Just now</div>
                    </div>
                    <div className="text-[#757575]">
                      Hello! I'm here to help you with the tree planting
                      process. What questions do you have?
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4 mt-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>YO</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[#4caf50]">You</div>
                      <div className="text-xs text-[#757575]">Just now</div>
                    </div>
                    <div className="text-[#757575]">
                      What are the best practices for planting trees?
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4 mt-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AI</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[#4caf50]">
                        Tree Planting Assistant
                      </div>
                      <div className="text-xs text-[#757575]">Just now</div>
                    </div>
                    <div className="text-[#757575]">
                      Great question! Here are some best practices for planting
                      trees:
                      <ul className="list-disc list-inside mt-2">
                        <li>
                          Choose the right tree species for your climate and
                          soil conditions
                        </li>
                        <li>
                          Dig a hole that is 2-3 times the width of the root
                          ball but no deeper
                        </li>
                        <li>
                          Gently loosen the roots before planting to encourage
                          growth
                        </li>
                        <li>
                          Water the tree thoroughly after planting and continue
                          watering regularly
                        </li>
                        <li>
                          Mulch around the base of the tree to retain moisture
                        </li>
                        <li>
                          Stake the tree for the first year to provide support
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4 mt-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>YO</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[#4caf50]">You</div>
                      <div className="text-xs text-[#757575]">Just now</div>
                    </div>
                    <div className="text-[#757575]">
                      That's really helpful, thank you! Do you have any tips on
                      how to care for the tree after it's planted?
                    </div>
                  </div>
                </div>
                <div className="flex items-start gap-4 mt-4">
                  <Avatar className="w-10 h-10 border">
                    <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                    <AvatarFallback>AI</AvatarFallback>
                  </Avatar>
                  <div className="grid gap-1.5">
                    <div className="flex items-center gap-2">
                      <div className="font-semibold text-[#4caf50]">
                        Tree Planting Assistant
                      </div>
                      <div className="text-xs text-[#757575]">Just now</div>
                    </div>
                    <div className="text-[#757575]">
                      Absolutely, here are some tips for caring for your newly
                      planted tree:
                      <ul className="list-disc list-inside mt-2">
                        <li>
                          Water the tree regularly, especially during the first
                          year
                        </li>
                        <li>
                          Prune any dead or damaged branches to encourage
                          healthy growth
                        </li>
                        <li>
                          Apply a layer of mulch around the base of the tree to
                          retain moisture
                        </li>
                        <li>
                          Protect the tree from pests and diseases by monitoring
                          it regularly
                        </li>
                        <li>
                          Fertilize the tree in early spring to provide
                          nutrients for growth
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
